version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: flashcards-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_flashCards
      TZ: UTC
    ports:
      - "6033:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: